// src/modules/export.js — Multi-format data export (JSON/CSV/Markdown)

export function createExportModule({ storage, Core, Logger, getCounterModule }) {
    return {
        id: 'export',
        name: '数据导出',
        description: 'JSON / CSV / Markdown 多格式导出',
        icon: '📤',
        defaultEnabled: true,

        init() { Logger.info('ExportModule initialized'); },
        destroy() { Logger.info('ExportModule destroyed'); },
        onUserChange() {},

        _download(content, filename, type) {
            const blob = new Blob([content], { type });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = filename;
            a.click();
            URL.revokeObjectURL(url);
        },

        _getFilePrefix() {
            const user = Core.getCurrentUser().split('@')[0];
            const date = new Date().toISOString().slice(0, 10);
            return `gemini-counter-${user}-${date}`;
        },

        exportJSON() {
            const cm = getCounterModule();
            const data = {
                total: cm.state.total,
                totalChatsCreated: cm.state.totalChatsCreated,
                chats: cm.state.chats,
                dailyCounts: cm.state.dailyCounts,
                exportedAt: new Date().toISOString(),
            };
            this._download(JSON.stringify(data, null, 2), `${this._getFilePrefix()}.json`, 'application/json');
        },

        exportCSV() {
            const cm = getCounterModule();
            const header = 'Date,Messages,Chats,Flash,Thinking,Pro,Weighted';
            const rows = [];
            const sorted = Object.entries(cm.state.dailyCounts || {}).sort(([a], [b]) => a.localeCompare(b));
            let sumMsg = 0, sumChats = 0, sumF = 0, sumT = 0, sumP = 0, sumW = 0;
            for (const [date, entry] of sorted) {
                const msg = entry.messages || 0;
                const ch = entry.chats || 0;
                const bm = entry.byModel || { flash: 0, thinking: 0, pro: 0 };
                const f = bm.flash || 0, t = bm.thinking || 0, p = bm.pro || 0;
                const w = f * 0 + t * 0.33 + p * 1;
                const wStr = w % 1 === 0 ? String(w) : w.toFixed(2);
                rows.push(`${date},${msg},${ch},${f},${t},${p},${wStr}`);
                sumMsg += msg; sumChats += ch; sumF += f; sumT += t; sumP += p; sumW += w;
            }
            const swStr = sumW % 1 === 0 ? String(sumW) : sumW.toFixed(2);
            rows.push(`TOTAL,${sumMsg},${sumChats},${sumF},${sumT},${sumP},${swStr}`);
            this._download(header + '\n' + rows.join('\n') + '\n', `${this._getFilePrefix()}.csv`, 'text/csv');
        },

        exportMarkdown() {
            const cm = getCounterModule();
            const user = Core.getCurrentUser();
            const now = new Date().toISOString().slice(0, 10);
            const streaks = cm.calculateStreaks ? cm.calculateStreaks() : {};
            const lines = [
                '# Gemini Usage Report', '',
                `**User:** ${user} | **Exported:** ${now}`, '',
                '## Summary', '',
                '| Metric | Value |', '|--------|-------|',
                `| Total Messages | ${cm.state.total} |`,
                `| Chats Created | ${cm.state.totalChatsCreated} |`,
            ];
            if (streaks.current !== undefined) lines.push(`| Current Streak | ${streaks.current} days |`);
            if (streaks.best !== undefined) lines.push(`| Best Streak | ${streaks.best} days |`);
            lines.push('');

            const sorted = Object.entries(cm.state.dailyCounts || {}).sort(([a], [b]) => a.localeCompare(b));
            const last30 = sorted.slice(-30);
            if (last30.length > 0) {
                lines.push('## Daily Breakdown (Last 30 Days)', '',
                    '| Date | Messages | Flash | Thinking | Pro | Weighted |',
                    '|------|----------|-------|----------|-----|----------|');
                for (const [date, entry] of last30) {
                    const msg = entry.messages || 0;
                    const bm = entry.byModel || { flash: 0, thinking: 0, pro: 0 };
                    const f = bm.flash || 0, t = bm.thinking || 0, p = bm.pro || 0;
                    const w = f * 0 + t * 0.33 + p * 1;
                    const wStr = w % 1 === 0 ? String(w) : w.toFixed(1);
                    lines.push(`| ${date} | ${msg} | ${f} | ${t} | ${p} | ${wStr} |`);
                }
                lines.push('');
            }
            lines.push('---', '', '*Generated by Gemini Counter Pro*', '');
            this._download(lines.join('\n'), `${this._getFilePrefix()}.md`, 'text/markdown');
        },

        renderExportButtons(container) {
            const buttons = [
                { text: '📤 Export JSON', fn: () => this.exportJSON() },
                { text: '📊 Export CSV', fn: () => this.exportCSV() },
                { text: '📝 Export Markdown', fn: () => this.exportMarkdown() },
            ];
            buttons.forEach(b => {
                const btn = document.createElement('button');
                btn.className = 'settings-btn';
                btn.textContent = b.text;
                btn.onclick = b.fn;
                container.appendChild(btn);
            });
        },
    };
}
